# Site settings
title: "Ernest Baker | DevOps Engineer"
description: "A vain attempt to document my professional life"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Set avatar and photo location
resume_avatar:                  "true"
resume_avatar_photo: "https://avatars.githubusercontent.com/u/15437063?v=4" # "assets/images/avatar.jpg"

# Set the resume name and title
resume_name:                    "Ernest L. Baker"
resume_title:                   "DevOps Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ernestlbaker@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "719.229.7102"
resume_contact_address:         "Orange City, FL"

resume_header_contact_info:     "{{ site.resume_contact_email }} | {{ site.resume_contact_telephone }} | {{ site.resume_contact_address }}"
display_header_contact_info:    "false"


resume_header_intro: "<p>Welcome to my digital space where I share my adventures in systems engineering, Python automation, and infrastructure design that have helped organizations save countless hours and secure millions in funding. Dive into my portfolio to explore how my unique blend of military experience, technical expertise in virtualization and networking, and passion for 3D printing and homesteading shapes my approach to solving complex IT challenges across industries.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/crow50"
  # resume_twitter_url:           "http://twitter.com/"
  # resume_dribbble_url:          "https://dribbble.com/"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/ernestlbaker"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://ernestbaker.me"
  # resume_medium_url:            "https://medium.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
